### ISSUE TITLE
No points in interpolated pointcloud

### ISSUE THREAD

**Issue by Mnzs1701** [EPVelasco/lidar_camera_fusion#2]
Thank you for the great contribution, I was trying to test this on a Velodyne Puck LITE (16 Point) with a Spinnaker FLIR Camera (Blackfly S). The output matrix that was obtained after running the suggested calibration package is as follows:

```
--------------------------------------------------------------------
After 1000 iterations
--------------------------------------------------------------------
Average translation is:
0.00709106
   0.30344
  0.106444
Average rotation is:
   0.99984  0.0134891  0.0117732
-0.0128457   0.998506 -0.0531141
 -0.012472  0.0529544   0.998519
Average transformation is: 
   0.99984  0.0134891  0.0117732 0.00709106
-0.0128457   0.998506 -0.0531141    0.30344
 -0.012472  0.0529544   0.998519   0.106444
         0          0          0          1
Final rotation is:
 0.0125693  -0.999819 -0.0142852
-0.0531243  0.0135985  -0.998495
  0.998509  0.0133093 -0.0529438
Final ypr is:
  1.80313
 -1.62541
-0.246282
Average RMSE is: 0.0250422
RMSE on average transformation is: 0.0615788
```

With this in mind the params file was written as follows:

```
camera_matrix: [2.30402682e+03, 0.00000000e+00, 1.02375433e+03,
0.00000000e+00, 2.30541892e+03, 7.42403621e+02, 
0.00000000e+00, 0.00000000e+00, 1.00000000e+00,]

# Final
rlc: [ 0.0125693,  -0.999819, -0.0142852,
-0.0531243,  0.0135985,  -0.998495,
  0.998509,  0.0133093, -0.0529438]

# Average  
# rlc: [0.99984 , 0.0134891,  0.0117732,
# -0.0128457,   0.998506, -0.0531141,
#  -0.012472,  0.0529544 ,  0.998519]

tlc: [ 0.00709106, 0.30344, 0.10644]
```

When using the final rotation matrix the output has only a couple of points (which are rotated) in the top left corner and it appears not to be the correct tranformation
![Screenshot from 2022-10-10 17-00-39](https://user-images.githubusercontent.com/43721824/194858471-2123f11b-5c28-435e-b38e-a86e5698afb0.png)

When using the average rlc values, the resulting pointcloud has no points visible. 

Is there some additional rotation that needs to be done in the rotation matrix provided by the code? Is there something wrong with my extrinsic? Any help would be appreciated

**Comment by Mnzs1701** [comment]
After rechecking, I was able to figure out an error in my camera matrix.

The configuration files need to be as follows:

1. Camera Matrix is a 3x4 Projection Matrix (My incorrect configuration was a 3x3 matrix that caused the error)
2. The "average" rotation and translation matrices need to be entered into the config file 

After the above two changes the code runs perfectly with the following output:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/43721824/194915688-49a3c744-dc66-4480-a14a-0e83df9a1e41.png">

Note: The code was tested on ROS Noetic as well and works great

**Comment by EPVelasco** [comment]
Hi, thank you for using my code.
I would appreciate if you put a star in the repository. We use this as a measure of the impact factor of the repository in the scientific community.

**Comment by stanny880913** [comment]
> After rechecking, I was able to figure out an error in my camera matrix.
> 
> The configuration files need to be as follows:
> 
> 1. Camera Matrix is a 3x4 Projection Matrix (My incorrect configuration was a 3x3 matrix that caused the error)
> 2. The "average" rotation and translation matrices need to be entered into the config file
> 
> After the above two changes the code runs perfectly with the following output: <img alt="image" width="971" src="https://user-images.githubusercontent.com/43721824/194915688-49a3c744-dc66-4480-a14a-0e83df9a1e41.png">
> 
> Note: The code was tested on ROS Noetic as well and works great

hi , amy I ask so you use  "average" rotation and "final" translation matrices to do fusion?
thank you~
